#!/bin/bash
#SBATCH -J alpha4_clean_filtrationdim
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=100000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser-memory --filtration dimension --out alpha4_clean_fildim ../after_run/bitcoin74
