#!/bin/bash
#SBATCH -J advo_avgruns_count
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 48:00:00
#SBATCH -n 20

ml gcc 
ml cmake
cd flagser
./flagser-count ../17_advo.txt
./flagser-count ../28_advo.txt
