#!/bin/bash
#SBATCH -J fb_or_run
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=1000
#SBATCH -t 24:00:00
#SBATCH -n 20

cd flagser
./flagser --filtration dimension --out fb_test_dimension_filtration ../graphs/flag/facebook_mess_dim0.txt
