#!/bin/bash
#SBATCH -J usairport_or_run
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module load gcc
ml cmake
cd flagser
(mkdir -p build && cd build && cmake .. && make -j)
./test/run
./flagser --max-dim 3 --out advogato_maxdim ../graphs/flag/advogato_dim0.txt
