#!/bin/bash
#SBATCH -J all_otc_avg
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=100000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser

./flagser --approximate 100 --filtration max --out ../../../work/scratch/nl26togu/results/1 ../../../work/scratch/nl26togu/graphs_avgs/1
