#!/bin/bash
#SBATCH -J openflightjustcount
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=1000
#SBATCH -t 4:00:00
#SBATCH -n 20

grep -c graphs/after_run/moreno_1.txt
