#!/bin/bash
#SBATCH -J for_loop_moreno1
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=1000
#SBATCH -t 4:00:00
#SBATCH -n 20

for i in {1 ..2539}
do
grep -c '^i ' graphs/after_run/moreno_1.txt
done
