#!/bin/bash
#SBATCH -J wikiapprox
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=100000
#SBATCH -t 48:00:00
#SBATCH -n 20

cd flagser
./flagser --approximate 10000 --out wiki10k ../graphs/flag/wiki_elections_dim0.txt
