#!/bin/bash
#SBATCH -J all_advo_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out advo_1 1_noloops
./flagser --out advo_5 5_noloops
./flagser --out advo_8 8_noloops
./flagser --out advo_12 12_noloops
./flagser --out advo_18 18_noloops
