#!/bin/bash
#SBATCH -J all_alpha_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out alpha_1 ../alpha/1
./flagser --out alpha_3 ../alpha/3
./flagser --out alpha_5 ../alpha/5
./flagser --out alpha_7 ../alpha/7
./flagser --out alpha_8 ../alpha/8
