#!/bin/bash
#SBATCH -J all_fb_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out fb_1 ../fb/1
./flagser --out fb_3 ../fb/3
./flagser --out fb_2 ../fb/2
