#!/bin/bash
#SBATCH -J all_moreno_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out moreno_4 ../moreno/4
./flagser --out moreno_3 ../moreno/3
./flagser --out moreno_2 ../moreno/2
./flagser --out moreno_6 ../moreno/6
./flagser --out moreno_7 ../moreno/7
