#!/bin/bash
#SBATCH -J all_alpha_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out moreno_1 ../moreno/1
./flagser --out moreno_3 ../moreno/3
./flagser --out moreno_2 ../moreno/2
