#!/bin/bash
#SBATCH -J all_opsahl_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=100000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser-count --out opsahl_1 ../opsahl/1
./flagser-count --out opsahl_2 ../opsahl/2
