#!/bin/bash
#SBATCH -J all_otc_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=100000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --approximate 10000 --out otc_1 ../otc/1
./flagser --approximate 10000 --out otc_3 ../otc/3
