#!/bin/bash
#SBATCH -J all_otc_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out otc_1 ../otc/1
./flagser --out otc_3 ../otc/3
./flagser --out otc_5 ../otc/5
./flagser --out otc_7 ../otc/7
./flagser --out otc_9 ../otc/9
