#!/bin/bash
#SBATCH -J all_alpha_at_once
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml cmake
cd flagser
./flagser --out wiki_1 ../wiki/1
./flagser --out wiki_3 ../wiki/3
./flagser --out wiki_5 ../wiki/5
./flagser --out wiki_7 ../wiki/7
