#!/bin/bash
#SBATCH -J alpha_barcodes_python
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=20000
#SBATCH -t 48:00:00
#SBATCH -n 20

module purge
ml gcc
ml python/3.6.8
ripsertry.py
