#!/bin/bash
#SBATCH -J fb_barcodes_python
#SBATCH --mail-type=ALL
#SBATCH -e /home/nl26togu/errorfile.err.%j
#SBATCH -o /home/nl26togu/noerror.out.%j
#SBATCH --mem-per-cpu=10000
#SBATCH -t 24:00:00
#SBATCH -n 20

module purge
ml gcc
ml python/3.6.8
pip install --user cython
pip install --user ripser
#!/bin/python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ripser import ripser
from persim import plot_diagrams
data = pd.read_csv("graphs/facebook_mess_norm.txt", sep=" ")
dgms = ripser(data)['dgms']
plot_diagrams(dgms, show=True)
